spring:
    application:
        name: customer-service
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: create
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:9091
server:
    port: 9020

logging:
    level:
        org.springframework.security: TRACE
        org.springframework.security.oauth2: TRACE