server:
    port: 9091

spring:
    application:
        name: authserver
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update

logging:
    level:
        org.springframework.security: TRACE
        org.springframework.security.oauth2: TRACE